import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs'

import DisableSidebar from "@/components/side-bar/disableSidebar";
import DisableNavbar from "@/components/nav-bar/disableNavbar";

import SidebarProvider from "@/components/side-bar/sidebarProvider";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider>
          <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <SidebarProvider>
            <DisableSidebar/>
            <main className="w-full">
              <DisableNavbar />
              {children}
            </main>
          </SidebarProvider>
          </body>
      </ClerkProvider>
    </html>
  );
}
